export const HOME_PATH = "/";

export const BUTTON_EXCHANGE = "EXCHANGE";

export const listMock = [
  {
    ticker: "btc",
    name: "Bitcoin",
    image: "https://content-api.changenow.io/uploads/btc_1_527dc9ec3c.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "eth",
    name: "Ethereum",
    image: "https://content-api.changenow.io/uploads/eth_f4ebb54ec0.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "ethbsc",
    name: "Ethereum (Binance Smart Chain)",
    image: "https://content-api.changenow.io/uploads/ethbsc_ef444521c5.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "etharb",
    name: "Ethereum (Arbitrum)",
    image:
      "https://content-api.changenow.io/uploads/etharbitrum_796401be67.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "btc",
    name: "Bitcoin",
    image: "https://content-api.changenow.io/uploads/btc_1_527dc9ec3c.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "eth",
    name: "Ethereum",
    image: "https://content-api.changenow.io/uploads/eth_f4ebb54ec0.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "ethbsc",
    name: "Ethereum (Binance Smart Chain)",
    image: "https://content-api.changenow.io/uploads/ethbsc_ef444521c5.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "etharb",
    name: "Ethereum (Arbitrum)",
    image:
      "https://content-api.changenow.io/uploads/etharbitrum_796401be67.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "btc",
    name: "Bitcoin",
    image: "https://content-api.changenow.io/uploads/btc_1_527dc9ec3c.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "eth",
    name: "Ethereum",
    image: "https://content-api.changenow.io/uploads/eth_f4ebb54ec0.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "ethbsc",
    name: "Ethereum (Binance Smart Chain)",
    image: "https://content-api.changenow.io/uploads/ethbsc_ef444521c5.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "etharb",
    name: "Ethereum (Arbitrum)",
    image:
      "https://content-api.changenow.io/uploads/etharbitrum_796401be67.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "btc",
    name: "Bitcoin",
    image: "https://content-api.changenow.io/uploads/btc_1_527dc9ec3c.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "eth",
    name: "Ethereum",
    image: "https://content-api.changenow.io/uploads/eth_f4ebb54ec0.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "ethbsc",
    name: "Ethereum (Binance Smart Chain)",
    image: "https://content-api.changenow.io/uploads/ethbsc_ef444521c5.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "etharb",
    name: "Ethereum (Arbitrum)",
    image:
      "https://content-api.changenow.io/uploads/etharbitrum_796401be67.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "btc",
    name: "Bitcoin",
    image: "https://content-api.changenow.io/uploads/btc_1_527dc9ec3c.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "eth",
    name: "Ethereum",
    image: "https://content-api.changenow.io/uploads/eth_f4ebb54ec0.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "ethbsc",
    name: "Ethereum (Binance Smart Chain)",
    image: "https://content-api.changenow.io/uploads/ethbsc_ef444521c5.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: "etharb",
    name: "Ethereum (Arbitrum)",
    image:
      "https://content-api.changenow.io/uploads/etharbitrum_796401be67.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
];
